### PR TITLE
Return body AND whole message

### PR DESCRIPTION
**Pull request by trek-td**
just making everything tranquil consistently return header, body, whole message, error tuples.

### CODE REVIEW

**Review by jiri-td — APPROVED** [review]
This makes a lot of sense.

**Comment by jiri-td** [comment]
@trek-td It's shaping up nicely!

**Comment by trek-td** [comment]
on monday jiri, we probably need to have a mind meld and clean up this stuff. Now we know that:
ReadMessage() will pull the raw bytes off the wire
ReadHeader() will separate the header and the body
decodeMessage() will remove bytes from the beginning of the body so that it can be turned into a bson.Document
We should see if we can get away with not interpreting things at all.

**Comment by jiri-td** [comment]
Agreed.

**Pull request merged**
